/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.1 		*/
/*  Created On : 01-Aug-2020 1:14:01 AM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

USE `UDPT`
;

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `Hospital` CASCADE
;

DROP TABLE IF EXISTS `Invoice` CASCADE
;

DROP TABLE IF EXISTS `MedicalStaff` CASCADE
;

DROP TABLE IF EXISTS `Notification` CASCADE
;

DROP TABLE IF EXISTS `NotiReceiver` CASCADE
;

DROP TABLE IF EXISTS `Patient` CASCADE
;

DROP TABLE IF EXISTS `Session` CASCADE
;

DROP TABLE IF EXISTS `TemperatureLog` CASCADE
;

DROP TABLE IF EXISTS `UserAuthentication` CASCADE
;

DROP TABLE IF EXISTS `UserDetail` CASCADE
;

/* Create Tables */

CREATE TABLE `Hospital`
(
	`HospitalId` INTEGER NOT NULL AUTO_INCREMENT,
	`Name` VARCHAR(50) NOT NULL,
	`Address` VARCHAR(50) NOT NULL,
	`PhoneNumber` VARCHAR(10) NOT NULL,
	CONSTRAINT `PK_Hospital` PRIMARY KEY (`HospitalId` ASC)
)

;

CREATE TABLE `Invoice`
(
	`InvoiceId` VARCHAR(36) NOT NULL,
	`PatientId` INTEGER NOT NULL,
	`CreatedDate` VARCHAR(50) NOT NULL,
	`TotalCost` DECIMAL(19,4) NOT NULL,
	`Insurance` DECIMAL(19,4) NOT NULL,
	`ServicesFee` DECIMAL(19,4) NOT NULL,
	`ActualPay` DECIMAL(19,4) NOT NULL,
	CONSTRAINT `PK_Invoice` PRIMARY KEY (`InvoiceId` ASC)
)

;

CREATE TABLE `MedicalStaff`
(
	`StaffId` INTEGER NOT NULL,
	`HospitalId` INTEGER NOT NULL,
	CONSTRAINT `PK_MedicalStaff` PRIMARY KEY (`StaffId` ASC)
)

;

CREATE TABLE `Notification`
(
	`NotiId` INTEGER NOT NULL AUTO_INCREMENT,
	`CreatedDate` DATETIME NOT NULL,
	`CreatedUser` INTEGER NOT NULL,
	`Message` VARCHAR(1000) NOT NULL,
	CONSTRAINT `PK_Notification` PRIMARY KEY (`NotiId` ASC)
)

;

CREATE TABLE `NotiReceiver`
(
	`NotiId` INTEGER NOT NULL AUTO_INCREMENT,
	`UserId` INTEGER NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`NotiId` ASC)
)

;

CREATE TABLE `Patient`
(
	`PatientId` INTEGER NOT NULL,
	`HospitalId` INTEGER 	 NULL,
	`AssignedDoctor` INTEGER 	 NULL,
	`Status` VARCHAR(15) 	 NULL,
	`QrtStart` DATETIME 	 NULL,
	`QrtEnd` DATETIME 	 NULL,
	`DischargedDate` DATETIME 	 NULL,
	CONSTRAINT `PK_Patient` PRIMARY KEY (`PatientId` ASC)
)

;

CREATE TABLE `Session`
(
	`SessionId` VARCHAR(26) NOT NULL,
	`UserId` INT NOT NULL,
	`UserName` VARCHAR(50) NOT NULL,
	`ExpirationDate` DATETIME NOT NULL,
	CONSTRAINT `PK_Table1` PRIMARY KEY (`SessionId` ASC)
)

;

CREATE TABLE `TemperatureLog`
(
	`TempLogId` INTEGER NOT NULL AUTO_INCREMENT,
	`PatientId` INTEGER NOT NULL,
	`Temperature` NUMERIC(3,2) NOT NULL,
	`Date` DATETIME NOT NULL,
	CONSTRAINT `PK_TemperatureLog` PRIMARY KEY (`TempLogId` ASC)
)

;

CREATE TABLE `UserAuthentication`
(
	`UserId` INTEGER NOT NULL,
	`Email` VARCHAR(50) NOT NULL,
	`PhoneNumber` VARCHAR(10) NOT NULL,
	`Password` BLOB NOT NULL,
	`Salt` VARCHAR(25) NOT NULL,
	`ActivateState` BOOL NOT NULL DEFAULT 0,
	CONSTRAINT `PK_UserAuthentication` PRIMARY KEY (`UserId` ASC)
)

;

CREATE TABLE `UserDetail`
(
	`UserId` INTEGER NOT NULL AUTO_INCREMENT,
	`UUID` VARCHAR(36) NOT NULL,
	`Name` VARCHAR(50) NOT NULL,
	`Sex` VARCHAR(10) NOT NULL,
	`Address` VARCHAR(50) NOT NULL,
	`IdentityCode` VARCHAR(20) NOT NULL,
	`PhoneNumber` VARCHAR(10) NOT NULL,
	`Email` VARCHAR(50) NOT NULL,
	CONSTRAINT `PK_UserDetail` PRIMARY KEY (`UserId` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `MedicalStaff` 
 ADD CONSTRAINT `FK_MedicalStaff_Hospital`
	FOREIGN KEY (`HospitalId`) REFERENCES `Hospital` (`HospitalId`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `MedicalStaff` 
 ADD CONSTRAINT `FK_MedicalStaff_UserDetail`
	FOREIGN KEY (`StaffId`) REFERENCES `UserDetail` (`UserId`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Notification` 
 ADD CONSTRAINT `FK_Notification_UserDetail`
	FOREIGN KEY (`CreatedUser`) REFERENCES `UserDetail` (`UserId`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `NotiReceiver` 
 ADD CONSTRAINT `FK_NotiReceiver_Notification`
	FOREIGN KEY (`NotiId`) REFERENCES `Notification` (`NotiId`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `NotiReceiver` 
 ADD CONSTRAINT `FK_NotiReceiver_UserDetail`
	FOREIGN KEY (`UserId`) REFERENCES `UserDetail` (`UserId`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Patient` 
 ADD CONSTRAINT `FK_Patient_Hospital`
	FOREIGN KEY (`HospitalId`) REFERENCES `Hospital` (`HospitalId`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Patient` 
 ADD CONSTRAINT `FK_Patient_MedicalStaff`
	FOREIGN KEY (`AssignedDoctor`) REFERENCES `MedicalStaff` (`StaffId`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Patient` 
 ADD CONSTRAINT `FK_Patient_UserDetail`
	FOREIGN KEY (`PatientId`) REFERENCES `UserDetail` (`UserId`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `Session` 
 ADD CONSTRAINT `FK_Session_UserDetail`
	FOREIGN KEY (`UserId`) REFERENCES `UserDetail` (`UserId`) ON DELETE Restrict ON UPDATE Restrict
;

ALTER TABLE `TemperatureLog` 
 ADD CONSTRAINT `FK_TemperatureLog_Patient`
	FOREIGN KEY (`PatientId`) REFERENCES `Patient` (`PatientId`) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE `UserAuthentication` 
 ADD CONSTRAINT `FK_UserAuthentication_UserDetail`
	FOREIGN KEY (`UserId`) REFERENCES `UserDetail` (`UserId`) ON DELETE No Action ON UPDATE No Action
;

SET FOREIGN_KEY_CHECKS=1 
;
