ALTER EVENT EV_AUTO_DELETE_SESSION
ON SCHEDULE EVERY 1 HOUR
DO
	DELETE FROM `session` WHERE ExpirationDate < (NOW() + INTERVAL 1 HOUR);
ALTER EVENT EV_AUTO_DELETE_SESSION ENABLE;
ALTER EVENT EV_AUTO_DELETE_SESSION DISABLE;